apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-jm-sysadm-kuber-project
  labels:
    app: eks-lab4-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: eks-lab4-project
  template:
    metadata:
      labels: 
        app: eks-lab4-project
    
    spec:
      containers:
      - name: eks-lab4-project
        image: REPOSITORY_TAG
        resources:
          requests:
             memory: 50Mi
             cpu: 0.25

---
apiVersion: v1
kind: Service
metadata:
  name: lab4-jm-sysadm-kuber-project-svc

spec:
  selector:
    app: eks-lab4-project

  ports:
    - name: http
      port: 3000

  type: ClusterIP
