apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab4-jm-sysadm-kuber-project

spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab4-jm-sysadm-kuber-project
  template:
    metadata:
      labels: 
        app: lab4-jm-sysadm-kuber-project
    
    spec:
      containers:
      - name: lab4-jm-sysadm-kuber-project
        image: REPOSITORY_TAG
        resources:
          requests:
             memory: 50Mi
             cpu: 0.25

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: lab4-jm-sysadm-kuber-project-svc

# spec:
#   selector:
#     app: lab4-jm-sysadm-kuber-project

#   ports:
#     - name: http
#       port: 3000

#   type: ClusterIP
