apiVersion: apps/v1
kind: Service
metadata:
  name: lab4-nodeNext-app
  labels:
    app: ecs-project
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31000
  selector:
    app: ebs-project
