name: DAST (DEFAULT)

on:
  push:
    branches:
      - feature-jm-sysadm #main
      #- '**'
jobs:

    Zap_Scan:
        name: Scan ZAP website
        #needs: Deploy
        runs-on: ubuntu-latest
        steps:
          - name: ZAP Scan
            uses: zaproxy/action-full-scan@v0.12.0
            with:
                target: 'http://localhost:3000/' # 'https://www.zaproxy.org/'
