name: DAST (DEFAULT)

on:
  push:
    branches:
      - feature-jm-sysadm #main
      #- '**'
jobs:

  Deploy:
    name: Deploy Docker Image SaaS
    #needs: DockerScan
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Pull Docker
        run: |
          docker pull jmsysadm/nodejs
      
      - name: Stop and remove existing container
        run: |
          $containerName = "lab4-jm-sysadm"
          $containerStatus = docker ps --filter "name=$containerName" --format "{{.Names}}"

          if ($containerStatus -eq $containerName) {
              Write-Output "Container $containerName identificado, deteniendo servicios"
              docker stop $containerName
              docker rm $containerName
          } else {
              Write-Output "Container $containerName no existe"
          }

      - name: Run Docker container
        run: |
          Write-Output "Desplegando container actualizado"
          docker run -d --name lab4-jm-sysadm -p 3000:3000 jmsysadm/nodejs

  Zap_Scan:
      name: Scan ZAP website
      needs: Deploy
      runs-on: self-hosted
      steps:

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker OWASP ZAP
        run: |
          docker pull zaproxy/zap-stable

      - name: Run ZAP SCAN container
        run: |
          Write-Output "Ejecutando ZAP Scan..."
          #docker run -v ${PWD}:/zap/wrk/:rw --network="host" zaproxy/zap-stable zap-baseline.py -t http://localhost:3000 -r scan-report.html
          docker run --network=host -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://127.0.0.1:3000 -I
