name: Docker CI/CD v1

on:
  push:
    branches:
      - none # feature-jm-sysadm #main
      #- '**'
jobs:
    DockerBuild:
        runs-on: ubuntu-latest
        steps:
        
        - name: Checkout code
          uses: actions/checkout@v4
          with:
              fetch-depth: 0

        - name: Install Dependency project
          run: npm install

        - name: Compile project with Next
          run: |
              if [ -f "package.json" ]; then
                echo "Proyecto utiliza archivo package.json"
                echo "Se habilita permiso de ejecución de archivo packsge.json"
                chmod 777 package.json
                npm run build
              else 
                echo "Otro tipo de proyecto"
              fi 

        - name: List Directory
          run: |
             if [ -d "./next" ]; then
                echo "Se identifica el directorio de proyecto Next - Compilados"
              else 
                echo "No se encuentra el proyecto Compilados"
              fi

        - name: Docker Login
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Download JAR
          run: |
            echo "En construcción - Download JAR"
          # uses: actions/download-artifact@master
          # with:
          #   name: JAR
          #   path: ${{github.workspace}}
    
        - name: Docker Build
          run: |
            echo "En construcción - Push Docker"
          # run: |
          #   ls -R
          #   docker build --tag b4b4y4g4x/cursodevsecops-test:latest .
    
        - name: Push Docker
          run: |
            echo "En construcción - Push Docker"
          # run: |
          #   docker push b4b4y4g4x/cursodevsecops-test:latest
    
    DockerScan:
        needs: DockerBuild
        runs-on: ubuntu-latest
        steps:
        
        - name: Docker Login
          uses: docker/login-action@v3.0.0
          with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        
        - name: Pull Docker
          run: |
            echo "En construcción - Pull Docker"
          # run: |
          #   docker pull b4b4y4g4x/cursodevsecops-test:latest
    
        - name: Run Trivy Scan
          run: |
            echo "En construcción - Docker Scan"
          # uses: aquasecurity/trivy-action@master
          # with:
          #   image-ref: 'b4b4y4g4x/cursodevsecops-test:latest'
          #   format: 'table'
    
    Deploy:
        needs: DockerScan
        runs-on: ubuntu-latest
        steps:
          - name: Ejecución de Proceso de despliegue de código
            run: |
              echo "En construcción - Docker Scan"
        